### ISSUE TITLE
Konnection completions available during a given session are static, "as of startup" only

### ISSUE THREAD

**Issue by therden** [dagraham/etm-dgraham#10]
The pop up Konnection completions that are offered after one enters `@k ` don't reflect the *current* state of journal records in the database, but rather their state *when the current `etm` session began*.

No pertinent changes made to database records *during* a session -- not new journal created records with `@i` index values, nor existing journal records with `@i` index values added, nor changes to the `@i` values of existing journal records -- are reflected in the Konnection pop up completions offered within that session.

**Comment by dagraham** [comment]
This should be fixed in the next release. I'll leave this open pending your confirmation that the problem has been corrected.

**Comment by therden** [comment]
When making a Konnection in Version 4.7.6, tab completions do now reflect new `@i` index values assignments made during the current session -- whether this was the first instance that an `@i `value was assigned or if a previous `@i` value is updated.  

However, when an `@i` index value is updated, the previous value continues to be displayed when an `@k ` entry invokes tab completions later during the same session.

**Comment by dagraham** [comment]
Making sure that the list of completions includes those in an reminder that is being saved is fairly straight forward since all it requires is the item and the set of saved completions. Making sure that the set of completions does not include any that are not present in at least one reminder is much more work because it requires checking all reminders to make sure the completion is in none of them. E.g., you might edit a reminder and change the index entry from "Smith, John"  to "Smith, Joan" but you would not want the completion for "Smith, John" to be removed without making sure that "Smith, John" is not used in any other reminder. I think this would be too much of a performance hit.
- Dan

**Comment by therden** [comment]
Wouldn't a TinyDB query with a custom test be sufficiently performant?

index_value = "@i Smith, John"               # using your example
test_func = lambda s: index_value in s    # Python's "in" is *fast*
found_in_db = self.db.search(Query().summary.test(test_func))
if not found_in_db:
    self.completions.remove(index_value)

**Comment by dagraham** [comment]
There are two issues that make what you suggest a little complicated. The first is that "i" is not the only entry for which completions are supported. The entire completions list is 'c', 'g', 'i', 'k', 'l', 'n', 't'. The second is that etm does not currently keep a copy of the entry being edited. It would be necessary to keep a list of the initial entries for each entry in this list and, on saving, do the sort of query you propose for each entry that has been modified. Would you like to submit a PR to do all this?

**Comment by therden** [comment]
Hi @dagraham.  

I'd be willing to take a look at it this weekend.  

I don't have much of a handle on the overall organization of the project's code.  Are the pertinent parts all within `data.py` or, if not, would you be willing to provide some hints about what to look at in which files?

**Comment by dagraham** [comment]
Have a look at 4.7.7 when you have a chance and let me know what you think. I think it fixes the issue of making completions consistent with the current data.

**Comment by dagraham** [comment]
Having heard nothing more, I assume 4.7.7 fixed the problem.
