### ISSUE TITLE
Over-aggressive overwrite of already-assigned &i index values of @j jobs

### ISSUE THREAD

**Issue by therden** [dagraham/etm-dgraham#13]
When the first `@j` job listed in an item has no index value, the application overwrites any `&i` index values already assigned to subsequent jobs in that item.  This plays havoc with any already-assigned `&p` prerequisite values.

It would be better if the application auto-assigned as-yet-unused `&i` index values only to the `@j` jobs that lack them.

**Comment by dagraham** [comment]
In the next release, if the first job does not have an &i entry, but a subsequent job does have an &i entry, a save will be aborted and the edit mode restored with a warning that in auto mode (no &i in the first job), none of the subsequent jobs should have &i entries.
