### ISSUE TITLE
"Save changes and close" silently discards @j Jobs that lack &i index values

### ISSUE THREAD

**Issue by therden** [dagraham/etm-dgraham#14]
When the first `@j` job listed in a task has an `&i` index value, but one or more `@j` jobs listed later in the item have none, the "Save changes and close" process **discards** the jobs which lack an `&i` index value **without warning**.

It would be better if, in that circumstance, the application alerted the user that all `@j` jobs require an `&i` index value and returned to Edit mode.

**Comment by dagraham** [comment]
This will be fixed in the next release.
