### ISSUE TITLE
"unrecorded timers"

### ISSUE THREAD

**Issue by gour** [dagraham/etm-dgraham#15]
Hello,

when I'm closing Etm, I get the following dialog:

![etm-unrecorded-timers](https://user-images.githubusercontent.com/114592/175803911-39fca1d9-ea1a-4e75-908a-5caf33a8b666.png)

Any idea?

**Comment by dagraham** [comment]
I just noticed this - sorry for the delay. When a timer is active (running or paused and thus not recorded) and etm is stopped, the state of the timer(s) is recorded to 'timers.pkl' in the home directory. The state(s) will be restored when etm is next restarted. Open timers view and delete the timers (TD) to avoid seeing this reminder.
