### ISSUE TITLE
Backtrace at startup if machine has only a non-US "en" locale enabled.

### ISSUE THREAD

**Issue by rxxrc** [dagraham/etm-dgraham#6]
Arch Linux 5.6.15-arch1-1 x86_64, using a freshly cloned master branch `c4cfdfd Tagged version 4.6.7.`

`$ETMHOME` is set to point to an empty directory.

I have only the Australian English locale enabled on my machine; notably *not* en_US:
```
$ locale -a
C
en_AU.utf8
POSIX
```

Running *etm* with `python -m etm` gives a traceback immediately:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "[REDACTED]/etm-dgraham/etm/__main__.py", line 273, in <module>
    main()
  File "[REDACTED]/etm-dgraham/etm/__main__.py", line 96, in main
    dataview = model.DataView(etmdir)
  File "[REDACTED]/etm-dgraham/etm/model.py", line 1922, in __init__
    self.currcal()
  File "[REDACTED]/etm-dgraham/etm/model.py", line 2874, in currcal
    self.refreshCalendar()
  File "[REDACTED]/etm-dgraham/etm/model.py", line 2845, in refreshCalendar
    cal.append(c.formatmonth(y, m+i, w=2).split('\n'))
  File "/usr/lib/python3.8/calendar.py", line 358, in formatmonth
    s = self.formatmonthname(theyear, themonth, 7 * (w + 1) - 1)
  File "/usr/lib/python3.8/calendar.py", line 582, in formatmonthname
    with different_locale(self.locale):
  File "/usr/lib/python3.8/calendar.py", line 552, in __enter__
    _locale.setlocale(_locale.LC_TIME, self.locale)
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

with log output:
```
######## Initializing logging #########
--- 2020-08-10 19:56:29,102 - CRITICAL - options.setup_logging
    logging at level: 20
    logging to file: [REDACTED]/logs/etm.log
--- 2020-08-10 19:56:29,133 - INFO - options.__init__
    updated [REDACTED]/cfg.yaml: missing [REDACTED]/cfg.yaml - using defaults
--- 2020-08-10 19:56:29,133 - INFO - __main__.main
    running in a virtual environment: False
--- 2020-08-10 19:56:29,255 - ERROR - model.set_etmdir
    could not set locale to en_US.UTF-8
--- 2020-08-10 19:56:29,255 - INFO - model.set_etmdir
    items: 0; archive: 0
--- 2020-08-10 19:56:29,255 - INFO - model.possible_archive
    archive_after: 0 - skipping archive
--- 2020-08-10 19:58:16,234 - CRITICAL - options.setup_logging
```

The problem seems to be caused by `model.py:1948`: 

https://github.com/dagraham/etm-dgraham/blob/c4cfdfdc392e51fa6f5f556b9f0247d13f49be5b/etm/model.py#L1948

which assumes `en_US` will be enabled if the config locale is set to `en`. This incorrect locale is then used via `DataView.cal_locale` to construct a `calendar.LocaleTextCalendar`:

https://github.com/dagraham/etm-dgraham/blob/c4cfdfdc392e51fa6f5f556b9f0247d13f49be5b/etm/model.py#L2835

which throws an exception when used:

https://github.com/dagraham/etm-dgraham/blob/c4cfdfdc392e51fa6f5f556b9f0247d13f49be5b/etm/model.py#L2845

I'm not familiar with the codebase so I'm not really sure what a good fix would be. A quick and dirty hack is to append 
```python
c.formatmonth(1970, 0)
```
directly after the construction of `c` (inside the try block) which will fail fast and fall back to whatever `calendar`'s default locale is instead. A more robust solution might involve adding an extra config key for a more specific locale or something.

**Comment by dagraham** [comment]
Many thanks for pointing this out. The version now available here on github will accept either 2 character or 5 character locale abbreviations in 'cfg.yaml'. E.g., 'en' will be accepted as 'en' without being converted to 'en_US'  and  'en_AU'  will also be accepted. When you have time, please let me know if this fixes the problem.

Thanks,
Dan

**Comment by rxxrc** [comment]
Yep, that's working perfectly. Thanks!
